<?php

/**
 * @file
 * Module file for mmeu module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mmeu_form_system_site_maintenance_mode_alter(&$form, &$form_state) {
  $form['maintenance_mode_exclude_url'] = array(
    '#type' => 'textarea',
    '#title' => t('Exclude Urls'),
    '#description' => t("Enter pages to be shown to visitors in miantenance mode. Enter one page per line as Drupal paths. The '*' character is a wildcard. Example paths are %blog for the blog page and %blog-wildcard for every personal blog. %front is the front page.",
            array(
                '%blog' => 'blog',
                '%blog-wildcard' => 'blog/*',
                '%front' => '<front>'
              )
            ),
    '#default_value' => variable_get('maintenance_mode_exclude_url', ''),
  );
}

/**
 * Implements hook_menu_site_status_alter().
 */
function mmeu_menu_site_status_alter(&$menu_site_status, $path) {
  if ($menu_site_status == MENU_SITE_OFFLINE && trim(variable_get('maintenance_mode_exclude_url', '')) != ''
     && drupal_match_path($path, variable_get('maintenance_mode_exclude_url'))) {
    $menu_site_status = MENU_SITE_ONLINE;
  }
}
